spring:
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5432/inventorydb-t1
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
            javax:
                persistence:
                    validation:
                        mode: none
